name: frontend_point_card_e2e_test_run

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  say_hello:
    if: github.event.client_payload.git.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "hello!"