name: frontend_point_card_e2e_test_run

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  debug_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context payload ref
        run: echo "github.event.client_payload.git.ref = ${{ github.event.client_payload.git.ref }}"
      - name: Dump GitHub context payload deployment client_payload
        run: echo "github.event.client_payload = ${{ toJson(github.event.client_payload) }}"
      - name: Dump GitHub context payload deployment project_name
        run: echo "github.event.client_payload.project.name = ${{ github.event.client_payload.project.name }}"
  say_hello:
    if: github.event.client_payload.git.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "hello!"